name: Open java-plugins PR

on:
  workflow_call:
    inputs:
      qosdk-version:
        type: string
        required: true
      quarkus-version:
        type: string
        required: true
      qosdk-bot-token:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: operator-framework/java-operator-plugins

      - name: Update QOSDK version to ${{inputs.qosdk-version}} in java-operator-plugins
        run: |
          sed -i -e 's|<quarkus-sdk.version>.*</quarkus-sdk.version>|<quarkus-sdk.version>${{inputs.qosdk-version}}</quarkus-sdk.version>|' $(pwd)/pkg/quarkus/v1beta/scaffolds/internal/templates/pomxml.go
          sed -i -e 's|<quarkus-sdk.version>.*</quarkus-sdk.version>|<quarkus-sdk.version>${{inputs.qosdk-version}}</quarkus-sdk.version>|' $(pwd)/testdata/quarkus/memcached-quarkus-operator/pom.xml
          
          echo "Using Quarkus ${{ inputs.quarkus-version }}"
          mvn versions:set-property -Dproperty=quarkus.version -DnewVersion=${{inputs.quarkus-version}} -f ./testdata/quarkus/memcached-quarkus-operator/pom.xml versions:commit
          sed -i -e 's|<quarkus.version>.*</quarkus.version>|<quarkus.version>${{inputs.quarkus-version}}</quarkus.version>|' $(pwd)/pkg/quarkus/v1beta/scaffolds/internal/templates/pomxml.go

      - name: Create java-operator-plugins pull request
        uses: peter-evans/create-pull-request@v5
        id: jop-pr
        with:
          title: "feat: update QOSDK to ${{inputs.qosdk-version}}"
          commit-message: "feat: update QOSDK to ${{inputs.qosdk-version}}"
          committer: metacosm <metacosm@users.noreply.github.com>
          author: metacosm <metacosm@users.noreply.github.com>
          branch: qosdk-release-${{inputs.qosdk-version}}
          token: ${{ inputs.qosdk-bot-token }}
          push-to-fork: qosdk-bot/java-operator-plugins
          delete-branch: true

      - name: Check java-operator-plugins PR
        if: ${{ steps.jop-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.jop-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.jop-pr.outputs.pull-request-url }}"