name: Build against latest JOSDK version

on:
  push:
    branches: [ next ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      quarkus-version:
        description: 'Quarkus version to build against'
        type: string
        required: false
        default: ''
      quarkus-pr:
        description: 'Quarkus PR number to use to run a QOSDK build with'
        type: string
        required: false

jobs:
  build-with-latest-josdk-snapshot:
    uses: ./.github/workflows/build-for-quarkus-version.yml
    with:
      quarkus-version: ${{inputs.quarkus-version}}
      quarkus-pr: ${{inputs.quarkus-pr}}
      java-version: 25
      branch: "next"
