name: Release snapshot of next-fabric8-version branch each day at midnight

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-for-latest-quarkus-version:
    uses: ./.github/workflows/build-for-quarkus-version.yml
    with:
      quarkus-version-jq-cmd: '.platforms[0]."current-stream-id" as $current | .platforms[0].streams[] | select(.id == $current) | .releases[0].version'
      java-version: 21
      branch: "next-fabric8-version"
      native-modules: "integration-tests,samples"
      profiles: "use-snapshots"

  release-snapshot:
    runs-on: ubuntu-latest
    needs:
      - build-for-latest-quarkus-version

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "next-fabric8-version"

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Set version to 999.F8-SNAPSHOT and release snapshot
        run: |
          mvn versions:set -DnewVersion=999.F8-SNAPSHOT versions:commit
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.GPG_PASSPHRASE}}" --output maven-settings.xml .github/release/maven-settings.xml.gpg
          mvn -B deploy -DperformRelease -Dno-samples -Prelease,use-snapshots -s maven-settings.xml